// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel0_C_drain_IO_L1_out (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fifo_C_drain_C_drain_IO_L1_out_0_193_dout,
        fifo_C_drain_C_drain_IO_L1_out_0_193_empty_n,
        fifo_C_drain_C_drain_IO_L1_out_0_193_read,
        fifo_C_drain_C_drain_IO_L1_out_0_092_din,
        fifo_C_drain_C_drain_IO_L1_out_0_092_full_n,
        fifo_C_drain_C_drain_IO_L1_out_0_092_write,
        fifo_C_drain_PE_0_088_dout,
        fifo_C_drain_PE_0_088_empty_n,
        fifo_C_drain_PE_0_088_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] fifo_C_drain_C_drain_IO_L1_out_0_193_dout;
input   fifo_C_drain_C_drain_IO_L1_out_0_193_empty_n;
output   fifo_C_drain_C_drain_IO_L1_out_0_193_read;
output  [127:0] fifo_C_drain_C_drain_IO_L1_out_0_092_din;
input   fifo_C_drain_C_drain_IO_L1_out_0_092_full_n;
output   fifo_C_drain_C_drain_IO_L1_out_0_092_write;
input  [15:0] fifo_C_drain_PE_0_088_dout;
input   fifo_C_drain_PE_0_088_empty_n;
output   fifo_C_drain_PE_0_088_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifo_C_drain_C_drain_IO_L1_out_0_193_read;
reg[127:0] fifo_C_drain_C_drain_IO_L1_out_0_092_din;
reg fifo_C_drain_C_drain_IO_L1_out_0_092_write;
reg fifo_C_drain_PE_0_088_read;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] add_ln1069_fu_117_p2;
reg   [4:0] add_ln1069_reg_155;
wire    ap_CS_fsm_state2;
wire   [1:0] add_ln870_fu_129_p2;
reg   [1:0] add_ln870_reg_163;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln1049_fu_135_p2;
reg   [0:0] icmp_ln1049_reg_168;
wire   [0:0] icmp_ln1069_10_fu_123_p2;
reg   [2:0] local_C_V_address0;
reg    local_C_V_ce0;
wire   [127:0] local_C_V_q0;
reg    local_C_V_ce1;
reg    local_C_V_we1;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_done;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_idle;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_ready;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_fifo_C_drain_PE_0_088_read;
wire   [2:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address0;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce0;
wire   [2:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address1;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce1;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_we1;
wire   [127:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_d1;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_done;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_idle;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_ready;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_193_read;
wire   [127:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_write;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_done;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_idle;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_ready;
wire   [127:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_write;
wire   [2:0] grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_address0;
wire    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_ce0;
reg   [1:0] c4_V_reg_70;
wire    ap_CS_fsm_state6;
reg    ap_block_state6_on_subcall_done;
wire    ap_CS_fsm_state4;
reg    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg;
wire   [0:0] icmp_ln1069_fu_111_p2;
wire    ap_CS_fsm_state3;
reg    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg;
reg    grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg;
reg   [4:0] indvar_flatten7_fu_62;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg = 1'b0;
#0 grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg = 1'b0;
#0 grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg = 1'b0;
end

kernel0_C_drain_IO_L1_out_boundary_wrapper12_local_C_V #(
    .DataWidth( 128 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_C_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_C_V_address0),
    .ce0(local_C_V_ce0),
    .q0(local_C_V_q0),
    .address1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address1),
    .ce1(local_C_V_ce1),
    .we1(local_C_V_we1),
    .d1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_d1)
);

kernel0_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start),
    .ap_done(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_done),
    .ap_idle(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_idle),
    .ap_ready(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_ready),
    .fifo_C_drain_PE_0_088_dout(fifo_C_drain_PE_0_088_dout),
    .fifo_C_drain_PE_0_088_empty_n(fifo_C_drain_PE_0_088_empty_n),
    .fifo_C_drain_PE_0_088_read(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_fifo_C_drain_PE_0_088_read),
    .local_C_V_address0(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address0),
    .local_C_V_ce0(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce0),
    .local_C_V_q0(local_C_V_q0),
    .local_C_V_address1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address1),
    .local_C_V_ce1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce1),
    .local_C_V_we1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_we1),
    .local_C_V_d1(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_d1)
);

kernel0_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3 grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start),
    .ap_done(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_done),
    .ap_idle(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_idle),
    .ap_ready(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_ready),
    .fifo_C_drain_C_drain_IO_L1_out_0_193_dout(fifo_C_drain_C_drain_IO_L1_out_0_193_dout),
    .fifo_C_drain_C_drain_IO_L1_out_0_193_empty_n(fifo_C_drain_C_drain_IO_L1_out_0_193_empty_n),
    .fifo_C_drain_C_drain_IO_L1_out_0_193_read(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_193_read),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_din(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_din),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_full_n(fifo_C_drain_C_drain_IO_L1_out_0_092_full_n),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_write(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_write)
);

kernel0_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2 grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start),
    .ap_done(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_done),
    .ap_idle(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_idle),
    .ap_ready(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_ready),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_din(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_din),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_full_n(fifo_C_drain_C_drain_IO_L1_out_0_092_full_n),
    .fifo_C_drain_C_drain_IO_L1_out_0_092_write(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_write),
    .local_C_V_address0(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_address0),
    .local_C_V_ce0(grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_ce0),
    .local_C_V_q0(local_C_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1069_fu_111_p2 == 1'd0))) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg <= 1'b1;
        end else if ((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_ready == 1'b1)) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1069_10_fu_123_p2 == 1'd0) & (icmp_ln1049_fu_135_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_ready == 1'b1)) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1069_10_fu_123_p2 == 1'd0) & (icmp_ln1049_fu_135_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_ready == 1'b1)) begin
            grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c4_V_reg_70 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        c4_V_reg_70 <= add_ln870_reg_163;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten7_fu_62 <= 5'd0;
    end else if (((icmp_ln1069_10_fu_123_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten7_fu_62 <= add_ln1069_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln1069_reg_155 <= add_ln1069_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln870_reg_163 <= add_ln870_fu_129_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1069_10_fu_123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        icmp_ln1049_reg_168 <= icmp_ln1049_fu_135_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln1069_fu_111_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1069_fu_111_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((icmp_ln1049_reg_168 == 1'd1)) begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_din = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
        end else if ((icmp_ln1049_reg_168 == 1'd0)) begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_din = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
        end else begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_din = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
        end
    end else begin
        fifo_C_drain_C_drain_IO_L1_out_0_092_din = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((icmp_ln1049_reg_168 == 1'd1)) begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_write = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_fifo_C_drain_C_drain_IO_L1_out_0_092_write;
        end else if ((icmp_ln1049_reg_168 == 1'd0)) begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_write = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_092_write;
        end else begin
            fifo_C_drain_C_drain_IO_L1_out_0_092_write = 1'b0;
        end
    end else begin
        fifo_C_drain_C_drain_IO_L1_out_0_092_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1049_reg_168 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        fifo_C_drain_C_drain_IO_L1_out_0_193_read = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_fifo_C_drain_C_drain_IO_L1_out_0_193_read;
    end else begin
        fifo_C_drain_C_drain_IO_L1_out_0_193_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fifo_C_drain_PE_0_088_read = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_fifo_C_drain_PE_0_088_read;
    end else begin
        fifo_C_drain_PE_0_088_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1049_reg_168 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        local_C_V_address0 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_C_V_address0 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_address0;
    end else begin
        local_C_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln1049_reg_168 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        local_C_V_ce0 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_local_C_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_C_V_ce0 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce0;
    end else begin
        local_C_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        local_C_V_ce1 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_ce1;
    end else begin
        local_C_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        local_C_V_we1 = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_local_C_V_we1;
    end else begin
        local_C_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1069_fu_111_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln1069_10_fu_123_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1069_fu_117_p2 = (indvar_flatten7_fu_62 + 5'd1);

assign add_ln870_fu_129_p2 = (c4_V_reg_70 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state6_on_subcall_done = (((icmp_ln1049_reg_168 == 1'd1) & (grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_done == 1'b0)) | ((grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_done == 1'b0) & (icmp_ln1049_reg_168 == 1'd0)));
end

assign grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_870_1_VITIS_s_fu_81_ap_start_reg;

assign grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_906_2_fu_96_ap_start_reg;

assign grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start = grp_C_drain_IO_L1_out_Pipeline_VITIS_LOOP_918_3_fu_88_ap_start_reg;

assign icmp_ln1049_fu_135_p2 = ((c4_V_reg_70 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1069_10_fu_123_p2 = ((c4_V_reg_70 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1069_fu_111_p2 = ((indvar_flatten7_fu_62 == 5'd16) ? 1'b1 : 1'b0);

endmodule //kernel0_C_drain_IO_L1_out
